### ISSUE TITLE
Support for Windows Powershell 5.1?

### ISSUE THREAD

**Issue by AGregersen** [jborean93/PowerShell-Yayaml#2]
Hi

Any chance for support for Windows Powershell 5.1?

Cheers,
 Anders

**Comment by jborean93** [comment]
Unfortunately this library uses Assembly Load Contexts to achieve the assembly isolation of YamlDotNet. This feature is not present in .NET Framework that Windows PowerShell uses so I cannot achieve the same thing there.

**Comment by jborean93** [comment]
While it cannot use the ALC logic to avoid assembly conflicts the PR https://github.com/jborean93/PowerShell-Yayaml/pull/13 has added support for Windows PowerShell 5.1. It’ll be present in the next release of this module that I’m planning for this week.
