### ISSUE TITLE
Feature Request: ConvertFrom-Yaml -AsJSON

### ISSUE THREAD

**Issue by JustinGrote** [jborean93/PowerShell-Yayaml#20]
To avoid any eccentricities with PowerShell ETS, etc. in converting from YAML to JSON, provide a `-AsJSON` that can serialize the `YamlObject` once read into JSON and output as a string.

https://dotnetfiddle.net/TntEwC

**Comment by jborean93** [comment]
Have you tried using the YAML 1.2 JSON schema which is meant to be JSON friendly?

```ps
@{foo='bar';test=@(1, 2, 'three')} | ConvertTo-Yaml -Schema Yaml12JSON
# {"foo": "bar", "test": [1, 2, "three"]}
```

**Comment by JustinGrote** [comment]
No I was not aware that was a thing! Seems to have worked at least for my use case, thanks!

**Comment by jborean93** [comment]
There are a few builtin schemas, I've tried to document them under https://github.com/jborean93/PowerShell-Yayaml/blob/main/docs/en-US/about_YamlEmitting.md#schemas. Let me know if there is anything emitted by that schema that isn't valid JSON and I can look into it further.
