### ISSUE TITLE
Are you going to be able to release new versions for upstream? 

### ISSUE THREAD

**Issue by Jaykul** [jborean93/PowerShell-Yayaml#4]
The [13.3.1](https://github.com/aaubry/YamlDotNet/releases/tag/v13.3.1) release in particular has a couple of important-seeming fixes.

**Comment by jborean93** [comment]
I can certainly do so, let me have a look to see if it's affected by them and will create a new release if it is.

**Comment by jborean93** [comment]
Thanks for letting me know, `0.2.0` is live on the gallery now with this dependency bump https://www.powershellgallery.com/packages/Yayaml/0.2.0
